sources:
  - HelloBeagle
  - Pods/Beagle/iOS/Sources/Beagle/CodeGeneration/SourceryProtocols.swift
templates:
  - Pods/Beagle/iOS/Sources/Beagle/CodeGeneration/Templates
output:
  HelloBeagle/CodeGeneration/Generated